global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'iot-universal-agent'
    static_configs:
      - targets: ['ubi-secure-node-01:8000']
        labels:
          device_group: 'residential-beta'
